[project]
name = "intropythonprogramming"
version = "0.1.0"
requires-python = ">=3.12.7"
dependencies = [
    "ipykernel>=6.30.1",
    "ipympl>=0.9.7",
    "matplotlib>=3.10.6",
    "nbconvert>=7.16.6",
    "numpy>=2.3.3",
    "otter-grader>=6.1.6",
    "scipy>=1.16.2",
]
